version: '3.8'

services:
  unraid-stats:
    image: ghcr.io/xexsolutions/unraid-stats:latest
    container_name: unraid-stats
    ports:
      - "8085:8085"
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /boot/config:/host/boot/config:ro
      - /var/local/emhttp:/host/var/local/emhttp:ro
      - /mnt/user:/host/mnt/user:ro
      - /mnt/disk*:/host/mnt/disk*:ro
      - /mnt/cache:/host/mnt/cache:ro
      - /mnt/disks:/host/mnt/disks:ro