version: '3.8'

services:
  unraid-stats:
    image: ghcr.io/xexsolutions/unraid-stats:latest
    container_name: unraid-stats
    ports:
      - "8080:8080"
    restart: unless-stopped
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro